### ISSUE TITLE
some question about consistency in paper

### ISSUE THREAD

**Issue by Jnmz** [WangLukang/MSCD#1]
Dear author, may I ask the upper part of the MGCF block: exploring the module of image consistency? We are not very clear about its design principle. What is consistency, why can it be improved by doing so, and why can it be directly added to the difference feature？Why should change detection tasks explore consistency？
This is very important for our works and we look forward to your reply. Thanks

**Comment by WangLukang** [comment]
The consistency module is designed to enhance the consistency of features to highlight the background (unchanged), while the difference module emphasizes the foreground (changed). By integrating both consistent and difference features, it increases the distance between change and no-change, resulting in a more optimal classification boundary.

**Comment by Jnmz** [comment]
ok, I understand, thank you very much.
